# Generated by Django 4.2.3 on 2024-03-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=254)),
                ('state_county', models.CharField(blank=True, max_length=254, null=True)),
                ('city_town', models.CharField(blank=True, max_length=254)),
            ],
        ),
    ]
