# Generated by Django 4.2.3 on 2024-03-24 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('data', '0002_dataset_location_alter_dataset_uploaded_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapoint',
            name='entity_id',
        ),
        migrations.RemoveField(
            model_name='datapoint',
            name='value',
        ),
        migrations.AddField(
            model_name='datapoint',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='locations.location'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='VariableValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(blank=True, max_length=254, null=True)),
                ('data_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.datapoint')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.dataset')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.variable')),
            ],
        ),
    ]
